openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user sign-up and login.

paths:
  /api/v1/sign-up:
    post:
      summary: User Sign-Up
      description: Registers a new user and returns a 24-length array of words (each 4 characters long) and a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "john_doe"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        201:
          description: User successfully registered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: array
                    items:
                      type: string
                      minLength: 4
                      maxLength: 4
                    minItems: 24
                    maxItems: 24
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        400:
          description: Invalid input data.

  /api/v1/login:
    post:
      summary: User Login
      description: Authenticates a user and returns a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "john_doe"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        200:
          description: Successfully authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        401:
          description: Unauthorized - Invalid credentials.
