name: Linting Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Run ESLint in backend
        working-directory: ./common
        run: yarn lint

      - name: Install shared lib dependencies
        working-directory: ./libs/shared
        run: yarn install --frozen-lockfile

      - name: Run ESLint in shared lib
        working-directory: ./libs/shared
        run: yarn lint
